spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/personDb
    username: postgres
    password: postgres
    name: personDb
    hikari:
      connection-timeout: 0

  jpa:
    generate-ddl: off
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/master.xml

#     data-locations:
#       - classpath:db/testdata.sql

logging:
  pattern:
    console: -%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

http:
  client:
    url: https://rickandmortyapi.com




